---
title: "GSE266566 SDATA-24-03470"
subtitle: "GEO.data.processing"
---

# GENE.level
```{r genes, include=FALSE}

### DOWNLOAD the supplementary data files from GEO
### GSE266566 - gene level
##################################################
library(GEOquery)
#
gene.counts.file <- getGEOSuppFiles(GEO = "GSE266566", filter_regex ="COUNTS.rsem_human.genes_NRP1_KD_BrCa_llynam.txt", fetch_files = TRUE)
print(gene.counts.file)
#
gene.counts <- read.table(gzfile(rownames(gene.counts.file)[1], "rt"), header = TRUE, sep = "\t")
dim(gene.counts) #78894    55
class(gene.counts) #"data.frame"
gene.counts[1:5,1:5]
#
#
expected.counts <- as.matrix(gene.counts[,grep("counts",colnames(gene.counts))])
rownames(expected.counts) <- gene.counts$Ensembl.114.Gene.ID
colnames(expected.counts) <- gsub("counts.","",colnames(expected.counts))
expected.counts[1:5,1:5]
#
#
## https://github.com/rocanja/GSE266566_NRP1_KD_BrCa_llynam/tree/main/files
gene.lengths <- read.table("./files/Ensembl.114.gene.lengths.txt", header=T)
gene.lengths <- gene.lengths[rownames(expected.counts), ]
#  
#
meta.data <- data.frame(Sample = colnames(expected.counts),
                      Line = gsub("\\..*","",colnames(expected.counts)),
                      Type = gsub(".RNA.*","",colnames(expected.counts)),
                      Repeat = gsub(".*RNA\\.","",colnames(expected.counts)))
meta.data$Treat <- sub("^[^.]*.","",meta.data$Type)
meta.data
dim(meta.data) #52  5
#
#  
### process data with edgeR
##################################################
library(edgeR)
#
y<-DGEList(counts=floor(expected.counts),group=meta.data$Type,genes=gene.counts[,1:3])
y <- calcNormFactors(y) #TMM normalisation by default
#
not.detected<-apply(y$counts<1,1,all)
table(not.detected) 
#
cpm<-cpm(y,normalized.lib.sizes=TRUE,log=FALSE) 
log.cpm<-cpm(y,normalized.lib.sizes=TRUE,log=TRUE) 
#
fpkm<-rpkm(y,normalized.lib.sizes=TRUE,log=FALSE,gene.length=rowMeans(gene.lengths)) 
log.fpkm<-rpkm(y,normalized.lib.sizes=TRUE,log=TRUE,gene.length=rowMeans(gene.lengths))
#
#
##################################################
save.image("NRP1.v48-Ensembl.114-genes_2025-08-08.Rdata")
##################################################
rm(list=setdiff(ls(),c(""))) #clean workspace

```

<br>

***  

# TRANSCRIPT.level
```{r transcripts, include=FALSE}

### DOWNLOAD the supplementary data files from GEO
### GSE266566 - transcript level
##################################################
library(GEOquery)
#
tx.counts.file <- getGEOSuppFiles(GEO = "GSE266566", filter_regex ="COUNTS.rsem_human.transcripts_NRP1_KD_BrCa_llynam.txt", fetch_files = TRUE)
print(tx.counts.file)
#
tx.counts <- read.table(gzfile(rownames(tx.counts.file)[1], "rt"), header = TRUE, sep = "\t")
dim(tx.counts) #387954
class(tx.counts) #"data.frame"
#
#
expected.counts <- as.matrix(tx.counts[,grep("counts",colnames(tx.counts))])
rownames(expected.counts) <- tx.counts$Ensembl.114.Transcript.ID
colnames(expected.counts) <- gsub("counts.","",colnames(expected.counts))
expected.counts[1:5,1:5]
#
#
## https://github.com/rocanja/GSE266566_NRP1_KD_BrCa_llynam/tree/main/files
tx.lengths <- read.table("./files/Ensembl.114.tx.lengths.txt", header=T)
tx.lengths <- tx.lengths[rownames(expected.counts), ]
#  
#
isoPcts.file <- getGEOSuppFiles(GEO = "GSE266566", filter_regex ="ISOPCT.rsem_human.transcripts_NRP1_KD_BrCa_llynam.txt", fetch_files = TRUE)
print(isoPcts.file)
#
isoPcts <- read.table(gzfile(rownames(isoPcts.file)[1], "rt"), header = TRUE, sep = "\t")
dim(isoPcts) #
class(isoPcts) #"data.frame"
#
#
meta.data <- data.frame(Sample = colnames(expected.counts),
                      Line = gsub("\\..*","",colnames(expected.counts)),
                      Type = gsub(".RNA.*","",colnames(expected.counts)),
                      Repeat = gsub(".*RNA\\.","",colnames(expected.counts)))
meta.data$Treat <- sub("^[^.]*.","",meta.data$Type)
meta.data
dim(meta.data) #52  5
#
#
### process data with edgeR
##################################################
library(edgeR)
#
y<-DGEList(counts=floor(expected.counts),group=meta.data$Type,genes=tx.counts[,1:3])
y <- calcNormFactors(y) #TMM normalisation by default
#
not.detected<-apply(y$counts<1,1,all)
table(not.detected) 
#
cpm<-cpm(y,normalized.lib.sizes=TRUE,log=FALSE) 
log.cpm<-cpm(y,normalized.lib.sizes=TRUE,log=TRUE) 
#
fpkm<-rpkm(y,normalized.lib.sizes=TRUE,log=FALSE,gene.length=rowMeans(tx.lengths))
log.fpkm<-rpkm(y,normalized.lib.sizes=TRUE,log=TRUE,gene.length=rowMeans(tx.lengths)) 
#
#
##################################################
save.image("NRP1.v48-Ensembl.114-transcripts_2025-08-08.Rdata")
##################################################
rm(list=setdiff(ls(),c(""))) #clean workspace

```

<br>

***  

# R.session Info
```{r Rsession, echo=FALSE}

sessionInfo() #record the R and package versions used
#############################
#RStudio.Version()
# RStudio 2024.12.1+563 "Kousa Dogwood" Release (27771613951643d8987af2b2fb0c752081a3a853, 2025-02-02) for windows
# Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.12.1+563 Chrome/126.0.6478.234 Electron/31.7.7 Safari/537.36, Quarto 1.5.57
##############################
# R version 4.4.3 (2025-02-28 ucrt)
# Platform: x86_64-w64-mingw32/x64
# Running under: Windows 11 x64 (build 22631)
# 
# Matrix products: default
# 
# 
# locale:
# [1] LC_COLLATE=English_Australia.utf8  LC_CTYPE=English_Australia.utf8   
# [3] LC_MONETARY=English_Australia.utf8 LC_NUMERIC=C                      
# [5] LC_TIME=English_Australia.utf8    
# 
# time zone: Australia/Brisbane
# tzcode source: internal
# 
# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
# [1] dplyr_1.1.4   ggplot2_4.0.0
# 
# loaded via a namespace (and not attached):
#  [1] vctrs_0.6.5        cli_3.6.5          knitr_1.50         rlang_1.1.6        xfun_0.53         
#  [6] generics_0.1.4     S7_0.2.0           glue_1.8.0         colorspace_2.1-1   htmltools_0.5.8.1 
# [11] rsconnect_1.5.1    scales_1.4.0       rmarkdown_2.29     grid_4.4.3         evaluate_1.0.5    
# [16] tibble_3.3.0       fastmap_1.2.0      yaml_2.3.10        lifecycle_1.0.4    compiler_4.4.3    
# [21] RColorBrewer_1.1-3 pkgconfig_2.0.3    rstudioapi_0.17.1  farver_2.1.2       digest_0.6.37     
# [26] R6_2.6.1           tidyselect_1.2.1   pillar_1.11.0      magrittr_2.0.4     withr_3.0.2       
# [31] tools_4.4.3        gtable_0.3.6   
##############################

```

***