---
title: "Figure.0 SDATA-24-03470"
subtitle: "overview diagram"
---

```{r include=FALSE}

library(ggplot2)
library(dplyr)
#
level.order.treat<-c("siNT","siNRP1.3","siNRP1.5","shNT","shNRP1.3","shNRP1.5") 
#group.colors.treat<-c("darkorange","#E41A1C","purple","black","#0000FF","green")
group.colors.treat<-colorspace::desaturate(c("darkorange","#E41A1C","purple","black","#0000FF","green"),amount=0.15) #muted colors
scales::show_col(group.colors.treat)

```


```{r}

## Create data frame for rectangles
n_rows <- 6
n_cols <- 3
total_rects <- n_rows * n_cols
#
## Base size of rectangles
rect_width <- 3
rect_height <- 0.7
#
## labels
rect_labels<-rep(c('shNRP1 #5 (x3)','shNRP1 #3 (x3)','shNT (x3)','siNRP1 #5 (x3)','siNRP1 #3 (x3)','siNT (x3)'), times=3)
#
## Define blocks for labeling on left side (blocks of 3 rows)
df <- expand.grid(row = 1:n_rows, col = 1:n_cols) %>%
  arrange(col, row) %>%
  mutate(
    x = (col - 1) * (rect_width + 0.5), #horizontal spacing
    y = ifelse(row <= 3, row - 1, row - 1 + 0.5), 
    xmin = x,
    xmax = x + rect_width,
    ymin = rep(c(0,0.85,1.7, 3,3.85,4.7),3), #instead of y, manual definition worked best 
    ymax = ymin + rect_height,
    label = rect_labels,
    row_color = factor(row)  # Different color by row
  )
df
### 2 outlier samples removed: HS578T.shNRP1.3.3 and SUM159.siNRP1.5.1
df[14,'label']<-'shNRP1 #3 (x2)'
df[4,'label']<-'siNRP1 #5 (x2)'  
df
#
## Define left side block labels for every 3 rows
block_labels <- data.frame(
  block = c("NRP1.shRNA\n48 hrs\nafter seeding", "NRP1.siRNA\n72 hrs\npost transfection"),
  x = -0.3,             # Placed left outside rectangles
  y = c(1.2,4.2) #manual works better
)
block_labels
#
## Column headers
headers <- data.frame(
  col = 1:n_cols,
  x = (0:(n_cols - 1)) * (rect_width + 0.5) + rect_width / 2,
  #y = max(df$y) + rect_height * 1.5,
  y = max(df$ymax) + 0.35,
  header = c("SUM159PT", "MDA-MB-231", "HS578T")
)
#
## Define a color palette for rows
row_colors <- rev(group.colors.treat)
#
## combine plot
plot<-ggplot() +
  geom_rect(data = df, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, color = row_color, fill = row_color), linewidth=1.5) +
  geom_text(data = df, aes(x = xmin + rect_width/2, y = ymin + rect_height/2, label = label), size = 5, fontface = "bold") +
  geom_text(data = headers, aes(x = x, y = y, label = header), size = 6, fontface = "bold") +
  geom_text(data = block_labels, aes(x = x, y = y, label = block), size = 5, hjust = 1, fontface = "italic") +
  annotate(geom='text', x=-1.3, y=2.7, label='strand.specific\nmRNAseq\nPE.150bp', size = 5, hjust = 0.5, color='grey60')+
  scale_color_manual(values = row_colors) +
  scale_fill_manual(values = alpha(row_colors,0.2)) +
  theme_void() +
  theme(legend.position='none')+
  expand_limits(x = -2, y = max(headers$y))
plot

```

```{r}

### A4 page in inches: 8.3 x 11.7 inches --> width=15,height=21.14
dev.new(width=10, height=5, noRStudioGD = T, rescale='fixed')
#
plot
#
cowplot::save_plot("Figure0.pdf", plot = plot, base_width = 10, base_height = 5)

```


<br>

***  

# R.session Info


```{r Rsession, echo=FALSE}

sessionInfo() #record the R and package versions used
##############################
# R version 4.2.3 (2023-03-15 ucrt)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 10 x64 (build 19044)
# 
# Matrix products: default
# 
# locale:
# [1] LC_COLLATE=English_Australia.utf8  LC_CTYPE=English_Australia.utf8   
# [3] LC_MONETARY=English_Australia.utf8 LC_NUMERIC=C                      
# [5] LC_TIME=English_Australia.utf8    
# 
# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
# [1] cowplot_1.1.1  ggrepel_0.9.3  ggplot2_3.4.2  reshape2_1.4.4 edgeR_3.40.2   limma_3.54.2  
# 
# loaded via a namespace (and not attached):
#  [1] Rcpp_1.0.10                 locfit_1.5-9.7              lattice_0.20-45            
#  [4] Rsamtools_2.14.0            Biostrings_2.66.0           digest_0.6.31              
#  [7] R6_2.5.1                    GenomeInfoDb_1.34.9         plyr_1.8.8                 
# [10] stats4_4.2.3                Polychrome_1.5.1            evaluate_0.21              
# [13] pillar_1.11.0               zlibbioc_1.44.0             rlang_1.1.3                
# [16] rstudioapi_0.14             S4Vectors_0.36.2            Matrix_1.6-5               
# [19] rmarkdown_2.22              BiocParallel_1.32.5         stringr_1.5.0              
# [22] RCurl_1.98-1.12             DelayedArray_0.23.2         compiler_4.2.3             
# [25] rtracklayer_1.58.0          xfun_0.39                   pkgconfig_2.0.3            
# [28] BiocGenerics_0.44.0         htmltools_0.5.4             tidyselect_1.2.0           
# [31] SummarizedExperiment_1.28.0 tibble_3.2.1                GenomeInfoDbData_1.2.9     
# [34] IRanges_2.32.0              codetools_0.2-19            matrixStats_1.0.0          
# [37] XML_3.99-0.13               crayon_1.5.2                dplyr_1.1.2                
# [40] withr_2.5.0                 GenomicAlignments_1.34.1    bitops_1.0-7               
# [43] grid_4.2.3                  gtable_0.3.3                lifecycle_1.0.3            
# [46] magrittr_2.0.3              scales_1.4.0                cli_3.6.0                  
# [49] stringi_1.7.12              farver_2.1.1                XVector_0.38.0             
# [52] scatterplot3d_0.3-43        generics_0.1.3              vctrs_0.6.0                
# [55] rjson_0.2.21                restfulr_0.0.15             RColorBrewer_1.1-3         
# [58] tools_4.2.3                 Biobase_2.58.0              glue_1.6.2                 
# [61] MatrixGenerics_1.10.0       parallel_4.2.3              fastmap_1.1.1              
# [64] yaml_2.3.7                  colorspace_2.1-0            GenomicRanges_1.50.2       
# [67] knitr_1.43                  BiocIO_1.8.0               
##############################

```


***
